language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

script:
  - cmake --version
  - mkdir build && cd build
  - cmake ..
  - make
  - make CTEST_OUTPUT_ON_FAILURE=1 test

notifications:
  email: false
