language: cpp

matrix:
 include:
  # QT 5.9 LTS
  - os: linux
    dist: xenial
    compiler: gcc
    env:
     - QT_BASE=59
  - os: linux
    dist: xenial
    compiler: clang
    env:
     - QT_BASE=59
  - os: linux
    dist: xenial
    compiler: gcc
    env:
     - QT_BASE=511
  # QT 5.12 LTS
  - os: linux
    dist: xenial
    compiler: gcc
    env:
     - QT_BASE=512
  - os: linux
    dist: xenial
    compiler: clang
    env:
     - QT_BASE=512
  - os: osx
    compiler: clang

before_install:
  - if [ "$QT_BASE" = "59" ]; then sudo add-apt-repository ppa:beineri/opt-qt597-xenial -y; fi
  - if [ "$QT_BASE" = "511" ]; then sudo add-apt-repository ppa:beineri/opt-qt-5.11.3-xenial -y; fi
  - if [ "$QT_BASE" = "512" ]; then sudo add-apt-repository ppa:beineri/opt-qt-5.12.3-xenial -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get update -qq;
    else
      brew update;
    fi

install:
  # install libgl to fix `GL/gl.h: No such file` error of QT
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libgl1-mesa-dev; fi
  - if [ "$QT_BASE" = "59" ]; then sudo apt-get install -qq qt59base; source /opt/qt59/bin/qt59-env.sh; fi
  - if [ "$QT_BASE" = "511" ]; then sudo apt-get install -qq qt511base; source /opt/qt511/bin/qt511-env.sh; fi
  - if [ "$QT_BASE" = "512" ]; then sudo apt-get install -qq qt512base; source /opt/qt512/bin/qt512-env.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install qt5;
      brew link --force qt5;
      export Qt5_DIR=$(brew --prefix qt)/lib/cmake/Qt5
    fi

script:
  - mkdir build && cd build
  - cmake ../
  - make
  - ctest -V

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
