name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        # TODO: add windows-latest when QT supports MSVC2019 
        # or Github Actions supports MSVC2017 in windows-latest
        # windows builds also need specifying building 64bit target:
        # if [[ "$OSTYPE" == "msys" ]]; then export WINEXTRA="-DCMAKE_GENERATOR_PLATFORM=x64"; else export WINEXTRA=""; fi
        os: [ubuntu-latest, macOS-latest]
        # ubuntu uses g++ / macos uses clang ++
        qt: [5.9.8, 5.12.5, 5.13.2]
        exclude: 
          # exclude old qt version of macOS
          - {os: 'macOS-latest', qt: '5.9.8'}
          - {os: 'macOS-latest', qt: '5.12.5'}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    # TODO: remove this when Github Actions has Qt built-in in the future
    - name: Install Qt ${{ matrix.qt }}
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
    - name: Install OpenGL support for QT (Ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libgl1-mesa-dev
        
    - name: Debug build and test
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        cmake --build . --config Debug
        
    - name: Release build and test
      run: |
        rm -rf build && mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --config Release
        ctest -V
        
    - name: Upload to codecov
      if: success()
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
